// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }

    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux.',
        );
      case TargetPlatform.fuchsia:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAbYdaEiGe7YUR3PKNmzvUvYRmu7jko9JI',
    appId: '1:25991115139:web:31758ab17180dda86d46b6',
    messagingSenderId: '25991115139',
    projectId: 'foodhub-7e959',
    authDomain: 'foodhub-7e959.firebaseapp.com',
    storageBucket: 'foodhub-7e959.firebasestorage.app',
    measurementId: 'G-FTBLNM3JTJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZtFI-25u1KXAfgQ0Af9QtP2-LUEFomvc',
    appId: '1:25991115139:android:c182abc561fae52a6d46b6',
    messagingSenderId: '25991115139',
    projectId: 'foodhub-7e959',
    storageBucket: 'foodhub-7e959.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDiUn33vkCGBxY3sq5OwL3RDrLeI7ObpuM',
    appId: '1:25991115139:ios:3b4d5cd83cff116d6d46b6',
    messagingSenderId: '25991115139',
    projectId: 'foodhub-7e959',
    storageBucket: 'foodhub-7e959.firebasestorage.app',
    iosBundleId: 'com.example.adminWebPortal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDiUn33vkCGBxY3sq5OwL3RDrLeI7ObpuM',
    appId: '1:25991115139:ios:3b4d5cd83cff116d6d46b6',
    messagingSenderId: '25991115139',
    projectId: 'foodhub-7e959',
    storageBucket: 'foodhub-7e959.firebasestorage.app',
    iosBundleId: 'com.example.adminWebPortal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAbYdaEiGe7YUR3PKNmzvUvYRmu7jko9JI',
    appId: '1:25991115139:web:02e7cb4b7659a3d96d46b6',
    messagingSenderId: '25991115139',
    projectId: 'foodhub-7e959',
    authDomain: 'foodhub-7e959.firebaseapp.com',
    storageBucket: 'foodhub-7e959.firebasestorage.app',
    measurementId: 'G-2HJPNXVJYM',
  );
}